Do not build when there are no updates in periodic pipelines
open-power-host-os/infrastructure pull request #101
Opened 2017-08-15 18:33 UTC by olavph

The pipeline will stop prematurely with a success if no updates are
detected.

2017-08-16 12:49 UTC, mopsfelder commented on pipeline/daily/stages.groovy
> +    Integer NO_UPDATES_EXIT_CODE = 56
Do you think it makes sense to place these constants on a lib?

2017-08-16 12:49 UTC, mopsfelder commented on pipeline/daily/stages.groovy
> +    }
The initial value of updateSuccessful is false, I think there is no need to set it again. What about the following?

```groovy
if (exitCode == SUCCESS_EXIT_CODE) {
  updateSuccessful = true
}

if (!updateSuccessful) {
  error('Packages update failed')
}
```

2017-08-16 12:49 UTC, mopsfelder commented on pipeline/devel.groovy
> +def execute(Boolean skipWithoutUpdates = false) {
The name skipWithoutUpdates gives me the idea that the pipeline will skip without touching or updating anything. I would have called it skipIfNoUpdates.

2017-08-16 13:44 UTC, olavph commented on pipeline/daily/stages.groovy
> +    }
We don't want to raise an error when NO_UPDATES_EXIT_CODE is returned. We don't want to do anything in that case. I just left the attribution there to make it clearer that the update did not happen, but I could leave it empty.

2017-08-16 13:44 UTC, olavph commented on pipeline/devel.groovy
> +def execute(Boolean skipWithoutUpdates = false) {
Ok

2017-08-16 13:44 UTC, olavph commented on pipeline/daily/stages.groovy
> +    Integer NO_UPDATES_EXIT_CODE = 56
This is the only place those are used so far. If we start using them elsewhere, it might be a good idea to create a `returncodes.groovy` file.

2017-08-16 14:07 UTC, farosas requested changes

2017-08-16 14:07 UTC, fabianorosas commented on pipeline/daily/stages.groovy
> +      updateSuccessful = true
I feel this makes things confusing down the line. Can't we invert the logic and set something like `hasUpdates` instead?

2017-08-16 14:11 UTC, olavph commented on pipeline/daily/stages.groovy
> +      updateSuccessful = true
Yeah, that's better. There's no logic to invert, renaming the variable is enough.

2017-08-17 14:00 UTC, farosas approved these changes

2017-08-17 18:42 UTC, merged