Parametrize jenkins user name
open-power-host-os/infrastructure pull request #119
Opened 2017-10-19 20:09 UTC by YasminBeatriz

Now jenkins master node has its own `jenkins-master` username. Same to jenkins slave node.

The job "Create slave node" is performed by master, but it uses the name of slave node's home directory. Therefore, it needs to have access to slave node's username, hence the `jenkins_slave_user_name` variable in `vars.yaml`.

2017-10-19 23:46 UTC, mopsfelder requested changes

2017-10-19 23:46 UTC, mopsfelder commented on ansible/roles/jenkins-master/tasks/main.yaml
> +  group: "{{user_name}}"
Are we sure this is working?  I've got the impression this owner and group are misplaced.

2017-10-19 23:46 UTC, mopsfelder commented on ansible/roles/jenkins-master/tasks/main.yaml
> +  group: root
Same here.

2017-10-19 23:46 UTC, mopsfelder commented on ansible/roles/jenkins-seed-job/tasks/main.yaml
> +    group: root
Why we are setting root:root for a Jenkins configuration file?

2017-10-23 19:33 UTC, olavph requested changes

2017-10-23 19:33 UTC, olavph commented on ansible/roles/jenkins-pipeline/templates/create_credentials_config.xml.j2
> +          <defaultValue>{{user_name}}</defaultValue>
Those are the credentials used to access the slaves, and so should contain the user name of those nodes, `{{jenkins_slave_user_name}}`

2017-10-23 19:33 UTC, olavph commented on ansible/roles/builds/tasks/main.yaml
>  - name: Create Host OS build directories
Explain in the commit message that "This improves isolation of the different user roles in a setup that creates master and slave in the same machine."

2017-10-27 18:24 UTC, olavph approved these changes

2017-10-27 19:19 UTC, merged