Allow weekly trigger to post comments in PRs
open-power-host-os/infrastructure pull request #33
Opened 2017-02-15 19:13 UTC by fabianorosas

The weekly trigger will post a comment to the pull-request of the weekly build to indicate that the ISO build should run for that PR.

2017-02-15 19:13 UTC, fabianorosas commented
Dear reviewers, this is on top of https://github.com/open-power-host-os/infrastructure/pull/31. Only last two commits are from this patchset.

2017-02-17 17:06 UTC, ghost requested changes

2017-02-17 17:06 UTC, olavphibm commented on scripts/github_api
> +        """
This file's modifications belong to the previous commit, which creates those functions.

2017-02-17 19:04 UTC, ghost approved these changes

2017-03-01 17:44 UTC, merged