Add Jenkins job which executes run host_os.py admin subcommands
open-power-host-os/infrastructure pull request #38
Opened 2017-02-22 20:50 UTC by alanoe

Also, trigger this Jenkins job when a GitHub pull request is
submitted to the builds git repository.

2017-03-03 00:43 UTC, ghost requested changes

2017-03-03 00:43 UTC, olavphibm commented on jenkins_jobs/run_host_os_admin_commands/script.sh
> +pushd $VERSIONS_REPO_DIR
The path to the versions repository is now `workspace/repositories/versions`.
See https://github.com/open-power-host-os/builds/pull/191/commits/38fa4129603377d5a632025e0367d1bfb9200c60#diff-4ef649d5da4e7f2fba8387f34f84d63fR21

2017-03-03 00:43 UTC, olavphibm commented on jenkins_jobs/run_host_os_admin_commands/script.sh
> +         --build-version $VERSIONS_REPO_COMMIT \
We're not gonna want those commits to be pushed. Use `--no-push-updates` for all commands.

2017-03-03 00:43 UTC, olavphibm commented on jenkins_jobs/run_host_os_admin_commands.groovy
> +  }
Since those commands are pretty fast to execute, we can probably allow concurrent builds in the same node. You can remove `throttleConcurrentBuilds`

2017-03-03 00:43 UTC, olavphibm commented on jenkins_jobs/trigger_host_os_admin_commands_from_builds_repo.groovy
> +  }
Do not remove this like above, it could cause deadlocks.

2017-03-03 00:43 UTC, olavphibm commented on jenkins_jobs/trigger_host_os_admin_commands_from_builds_repo.groovy
> +      triggerPhrase('.*start\\W+(tests|admin_commands).*')
Why not `\\W+` instead of `_` as separator?

2017-03-03 00:43 UTC, olavphibm commented on jenkins_jobs/trigger_host_os_admin_commands_from_builds_repo.groovy
> +	  context('Build Host OS')
`context('Administrative commands')` or something like that

2017-03-06 12:51 UTC, farosas approved these changes

2017-03-08 19:24 UTC, alanoe commented on jenkins_jobs/run_host_os_admin_commands.groovy
> +  }
Done

2017-03-08 19:29 UTC, alanoe commented on jenkins_jobs/trigger_host_os_admin_commands_from_builds_repo.groovy
> +      triggerPhrase('.*start\\W+(tests|admin_commands).*')
I have no preference. Done

2017-03-08 19:33 UTC, alanoe commented on jenkins_jobs/run_host_os_admin_commands/script.sh
> +pushd $VERSIONS_REPO_DIR
Done

2017-03-08 19:33 UTC, alanoe commented on jenkins_jobs/run_host_os_admin_commands/script.sh
> +         --build-version $VERSIONS_REPO_COMMIT \
Done

2017-03-08 19:57 UTC, ghost requested changes

2017-03-08 19:57 UTC, olavphibm commented on jenkins_jobs/run_host_os_admin_commands/script.sh
> +pushd repositories/$VERSIONS_REPO_DIR
The path is incorrect and is not the same where you're cloning.
```
VERSIONS_REPO_PATH="workspace/repositories/$VERSIONS_REPO_DIR"
git clone $VERSIONS_REPO_URL $VERSIONS_REPO_PATH --no-checkout
pushd $VERSIONS_REPO_PATH
```

2017-08-04 20:31 UTC, olavph commented
We are now using Jenkins pipelines, this will not be worked on.

2017-08-04 20:31 UTC, closed without merging