Add a Jenkins job which builds an ISO when a GitHub pull request is created
open-power-host-os/infrastructure pull request #39
Opened 2017-02-22 20:51 UTC by alanoe

2017-03-03 00:45 UTC, ghost requested changes

2017-03-03 00:45 UTC, olavphibm commented on jenkins_jobs/trigger_host_os_iso_build_from_builds_repo.groovy
> +			   VERSIONS_REPO_COMMIT: 'master'])
This will not work, the build_host_os_iso job needs a build_host_os job ID

2017-03-06 13:11 UTC, farosas requested changes

2017-03-06 13:11 UTC, fabianorosas commented on jenkins_jobs/trigger_host_os_iso_build_from_builds_repo.groovy
> +      triggerPhrase('.*start\\W+(tests|build_iso).*')
I used `triggerPhrase('.*start\\W+iso.*')` in the 'trigger_host_os_iso_from_versions' trigger. Also, the triggers for 'build_host_os' all use ` triggerPhrase('.*start\\W+(tests|build).*')`. That '.*' there in the end would make this job trigger a second 'build_host_os'

2017-03-06 13:11 UTC, fabianorosas commented on jenkins_jobs/trigger_host_os_iso_build_from_builds_repo.groovy
> +	  context('Build Host OS')
Build Host OS ISO

2017-03-06 13:11 UTC, fabianorosas commented on jenkins_jobs/trigger_host_os_iso_build_from_builds_repo.groovy
> +	  context('Build Host OS')
Add
`statusUrl('${JENKINS_URL}/job/build_host_os_iso/${TRIGGERED_BUILD_NUMBER_build_host_os_iso}')`
like the _from_versions trigger

2017-03-06 13:11 UTC, fabianorosas commented on jenkins_jobs/trigger_host_os_iso_build_from_builds_repo.groovy
> +			   VERSIONS_REPO_COMMIT: 'master'])
Need to add the script from the other trigger:

https://github.com/open-power-host-os/infrastructure/blob/master/jenkins_jobs/trigger_host_os_iso_build_from_versions_repo.groovy#L36

And the credentials binding plugin:

https://github.com/open-power-host-os/infrastructure/blob/master/jenkins_jobs/trigger_host_os_iso_build_from_versions_repo.groovy#L53

2017-06-02 16:39 UTC, olavph commented
This is superseded by #77

2017-06-02 16:39 UTC, closed without merging