Stop calling packages and ISO builds from trigger weekly
open-power-host-os/infrastructure pull request #41
Opened 2017-02-24 18:23 UTC by fabianorosas

The packages and ISO builds are already being run when a pull request is open. This PR alters the weekly trigger to stop calling these jobs and wait until the pull request is closed before continuing.

2017-02-24 18:23 UTC, fabianorosas commented
Last 2 commits to be reviewed

2017-03-02 16:46 UTC, ghost requested changes

2017-03-02 16:46 UTC, olavphibm commented on jenkins_jobs/trigger_weekly_host_os_build/pre_build_script.sh
> +echo "${TRIGGERED_JOB_NUMBER_build_host_os}" > BUILD_JOB_NUMBER
This script is executed before the build, so you do not have this number yet. You could use this variable directly in the `copy_artifacts.sh` scripts.

2017-03-02 16:46 UTC, olavphibm commented on jenkins_jobs/trigger_weekly_host_os_build/pre_build_script.sh
> +	           --push-repo-branch "$COMMIT_BRANCH"
Those lines have tabs, they are not aligned with `--build-versions-repository-url`

2017-03-03 00:22 UTC, ghost approved these changes

2017-03-03 15:19 UTC, merged