Alter weekly trigger job to create release tags in the git repos
open-power-host-os/infrastructure pull request #42
Opened 2017-02-27 18:25 UTC by fabianorosas

2017-02-27 18:26 UTC, fabianorosas commented
Last 4 commits only

2017-03-04 22:50 UTC, ghost requested changes

2017-03-04 22:50 UTC, olavphibm commented on jenkins_jobs/trigger_weekly_host_os_build/pre_build_script.sh
> +    local artifacts_src_build_number=$(basename $target_url)
It's hard to know where those variables are coming from. We should consider improving this format later.

2017-03-04 22:50 UTC, olavphibm commented on jenkins_jobs/trigger_weekly_host_os_build.groovy
> -	    'jenkins_jobs/trigger_weekly_host_os_build/post_build_script.sh'))
The other two script references should have been removed in the previous commit.

2017-03-04 22:50 UTC, olavphibm commented on jenkins_jobs/trigger_weekly_host_os_build/script.sh
> +VERSIONS="versions"
I'd name it `VERSIONS_REPO_NAME`

2017-03-04 22:50 UTC, olavphibm commented on jenkins_jobs/trigger_weekly_host_os_build/script.sh
> +GITHUB_IO="${GITHUB_ORGANIZATION_NAME}.github.io"
I'd name it `GITHUB_IO_REPO_NAME`

2017-03-04 22:50 UTC, olavphibm commented on jenkins_jobs/trigger_weekly_host_os_build/script.sh
> +               --build-versions-repository-url "$VERSIONS_PUSH_URL" \
This could be the HTTPS URL, but ok, there's no need to have two URLs for the versions repo.

2017-03-04 22:50 UTC, olavphibm commented on jenkins_jobs/trigger_weekly_host_os_build/script.sh
> +    local version_file="$(basename $VERSIONS_PUSH_URL .git)/VERSION"
The default versions repository location is no longer `versions`, it's `workspace/repositories/versions`.
Also, you have the repo name in a var, you don't need the `basename` command.

2017-03-04 22:50 UTC, olavphibm commented on jenkins_jobs/trigger_weekly_host_os_build/script.sh
> +        pushd $repo_name
Again, this would be `workspace/repositories/$repo_name`

2017-03-06 18:12 UTC, ghost approved these changes

2017-03-07 20:20 UTC, merged