Add information about builds and versions commit ids to STATUS file
open-power-host-os/infrastructure pull request #57
Opened 2017-04-04 13:00 UTC by fabianorosas

2017-04-04 13:05 UTC, ghost requested changes

2017-04-04 13:05 UTC, olavphibm commented on jenkins_jobs/upload_build_artifacts/script.sh
> +      'BUILDS_REPO_COMMIT': '$BUILDS_REPO_COMMIT' \
Missing comma

2017-04-04 13:56 UTC, fabianorosas commented on jenkins_jobs/upload_build_artifacts/script.sh
> +      'BUILDS_REPO_COMMIT': '$BUILDS_REPO_COMMIT' \
BTW, we should consider using actual JSON for this.

2017-04-04 17:54 UTC, ghost submitted a review, later dismissed

2017-04-06 13:08 UTC, olavphibm commented on jenkins_jobs/trigger_host_os_build_from_builds_repo.groovy
> +			   VERSIONS_REPO_REFERENCE: 'origin/master'])
There are other jobs mentioning only "master". Isn't it better to modify them too?
e.g. jenkins_jobs/trigger_yamllint_from_versions_repo.groovy, jenkins_jobs/trigger_weekly_host_os_build.groovy:

2017-04-06 14:28 UTC, ghost approved these changes

2017-04-06 14:36 UTC, merged