Improvements in Ansible and Jenkins jobs
open-power-host-os/infrastructure pull request #74
Opened 2017-05-16 20:21 UTC by olavph

2017-05-23 21:45 UTC, farosas requested changes

2017-05-23 21:45 UTC, fabianorosas commented on jenkins_jobs/trigger_nightly_host_os_build/post_build_script.sh
> +          $@ $ISO_DIR_RSYNC_URL
Isn't `$ISO_DIR_RSYNC_URL` out of place here?

2017-05-24 13:38 UTC, olavph commented on jenkins_jobs/trigger_nightly_host_os_build/post_build_script.sh
> +          $@ $ISO_DIR_RSYNC_URL
Yep. Fixing.

2017-05-24 13:50 UTC, farosas requested changes

2017-05-24 13:50 UTC, fabianorosas commented on jenkins_jobs/trigger_nightly_host_os_build/post_build_script.sh
> +rsync_upload "$NIGHTLY_DIR_NAME" "$NIGHLTY_DIR_RSYNC_URL/"
Maybe the idea is to have only `$@` up there?

2017-05-24 18:40 UTC, olavph commented on jenkins_jobs/trigger_nightly_host_os_build/post_build_script.sh
> +rsync_upload "$NIGHTLY_DIR_NAME" "$NIGHLTY_DIR_RSYNC_URL/"
The idea was actually to remove the second parameter, like in `upload_build_artifacts` and `upload_iso`. Fixing.

2017-05-24 20:01 UTC, farosas approved these changes

2017-05-24 20:22 UTC, merged

2017-05-24 20:24 UTC, mopsfelder commented
@olavph Nice improvements.  Thanks!